function []=PASTAInstructions(design)

fontcolor=design.grey;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'Welcome to the Alternative Uses Task.', ...
    'In this game, your task is to find alternative', ...
    'uses to various categories.', ...
    '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window); 
KbStrokeWait;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'On each trial, you will be presented with one category title on top of the screen', ...
    'Your task is to come up with UNUSUAL USES for that category.', ...
    'Once you are done reading the category title, press the space bar.', ...
    '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window); 
KbStrokeWait;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'When you press the space bar, you will see a green + sign in the middle of the screen.', ...
    'When the green + is there, come up with one UNUSUAL USE for that category. ', ...
    'Once you come up with an unusual use, say that outloud.', ...
    'The microphone icon means that we are recording your voice.', ...
    'Repeat these steps until your time ends.', ...
        '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window);
KbStrokeWait;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'You have a total of 3 minutes to come up with unusual uses for each category', ...
    'There are NO RULES to type of uses you can come up with.', ...
    'There are NO RIGHT OR WRONG answers.', ...
    'Try to come up with as many alternative uses as possible. ', ...
    'Throughout the experiment, please speak up ONLY when you have a new use', ...
    'and keep quiet otherwise.',...
    'Now press a key to practice the rules.'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window);
KbStrokeWait;